### ISSUE TITLE
Support multiple submissions and Display results

### ISSUE THREAD

**Issue by Web-Project-Administrator** [esnaveiro/voting-booth#4]
1. Allow the app to store several submissions from different devices (different tabs or windows)
2. Store all submissions
3. Create a button on the "admin" panel, when pressed it will display the results below the voting options on the main page. This way only the admin will be able to close the voting and the results will be revealed to every single user on the main page.
A simple text can be displayed for the MVP. for example:

A Favor: *7 votes*
Contra: *3 votes*
Abstenção: *0 votes*

Later on the goal is to make more of a friendly UI, so it should look something similar to one on the link below:
https://i.stack.imgur.com/7sFQd.png

**Comment by ppconde** [comment]
Can you test the current deployment? Everything should be implemented. Minor bugs can be fixed later
